#
# OpenVPN server sample configuration
#

version: '2.2' # Min version 2.1 for IPv6
services:
  ovpn:
    image: slocomptech/openvpn
    container_name: ovpn
    hostname: ovpn
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
    volumes:
      - ./data:/config
    #environment:
    #  - PUID=1000
    #  - PGUID=1000
    restart: on-failure
    build:
      context: .
    sysctls: # For IPv6
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.default.forwarding=1
      - net.ipv6.conf.all.forwarding=1

    network_mode: "bridge"
    #network_mode: "host"
    