#!/usr/bin/python

#
#   Config wizard for basic_nat_wlp example
#   @author Martin Dagarin
#   @version 1
#   @since 19/03/2019
#

#   Defaults:
#       Protocol: udp
#       Network: 10.0.0.0
#       Port: 1194
#       DNS: 8.8.8.8, 8.8.4.4
#

import sys, os

# Import libraries included in this docker
sys.path.insert(0, '/app')
import libovpn

# Check if temporary path was passed to this script
if len(sys.argv) < 2:
  print("Temporary path was not passed to wizard")
  sys.exit(1)
TEMP_PATH = sys.argv[1]
if not os.path.isdir(TEMP_PATH):
  print("Specified directory does not exist")
  sys.exit(2)

# Select output interface
out_int = input("Out interface [eth0]:")
if len(out_int) == 0:
  out_int = "eth0"

# Select protocol
protocol = input("Protocol udp, tcp, udp6, tcp6 [udp]:")
AVAILABLE_PROTOCOLS = ["udp", "tcp", "udp6", "tcp6"]
if len(protocol) != 0 and protocol not in AVAILABLE_PROTOCOLS:
  print("Invalid protocol")
  sys.exit(3)
if len(protocol) == 0:
  protocol = "udp"

# Select network
network = input("VPN network [10.0.0.0]:")
if len(network) == 0:
  network = "10.0.0.0"

# Select port
port = input("Port [1194]:")
if len(port) == 0:
  port="1194"

# Select Public IP or domain
public = input("Public IP or domain of server:")
if len(public) == 0:
  print("Invalid Public IP")
  sys.exit(4)

# DNS servers
dns1 = input("DNS1 [8.8.8.8]:")
if len(dns1) == 0:
  dns1 = "8.8.8.8"
dns2 = input("DNS2 [8.8.4.4]:")
if len(dns2) == 0:
  dns2 = "8.8.4.4"


# Write to server config
vars = [
  ("$OUT_INT", out_int),
  ("$PROTO", protocol),
  ("$PORT", port),
  ("$NETWORK_ADDRESS", network),
  ("$SERVER_IP", public),
  ("$DNS1", dns1),
  ("$DNS2", dns2)
]

# Process config files
confs = [
  "/config/openvpn/openvpn.conf",
  "/config/openvpn/openvpn-client.conf",
  "/config/openvpn/hooks/down/10-network.sh",
  "/config/openvpn/hooks/up/10-network.sh"
]
for config_file in confs:
  libovpn.conf_envsubst(TEMP_PATH + config_file, vars)