#!/usr/bin/with-contenv bash
#
# Config wizard for basic_s2s example
# @author Martin Dagarin
# @version 1
# @since 20/03/2020
#

set -e
source $CONTAINER_VARS_FILE

if [ -z "$1" ]; then
  echo 'Directory path missing'
  exit 1
fi

read -p 'Protocol udp, tcp, udp6, tcp6 [udp]: ' protocol
protocol=${protocol:-udp}

read -p 'Port [1194]: ' port
port=${port:-1194}

read -p 'Site A public IP: ' remote_a
[ -z "$remote_a" ] && { echo 'Invalid IP'; exit 2; }

read -p 'Site A tunnel IP: ' ip_a
[ -z "$ip_a" ] && { echo 'Invalid IP'; exit 2; }

read -p 'Site B public IP: ' remote_b
[ -z "$remote_b" ] && { echo 'Invalid IP'; exit 2; }

read -p 'Site B tunnel IP: ' ip_b
[ -z "$ip_b" ] && { echo 'Invalid IP'; exit 2; }

confs=(
  "$1/config/openvpn/openvpn.conf"
  "$1/config/openvpn/openvpn-template.conf"
)

for file in "${confs[@]}"
do
  $RUNCMD mv $file $file.old
  PROTO="$protocol" \
  PORT="$port" \
  REMOTE_A="$remote_a" \
  IP_A="$ip_a" \
  REMOTE_B="$remote_b" \
  IP_B="$ip_b" \
  $RUNCMD envsubst < $file.old > $file
  $RUNCMD rm $file.old
done
