#!/usr/bin/with-contenv bash

source /app/lib/settings

#
#   Network setup
#

# Delete tunnel interface (if not persistant)
intTunExists
TUNE=$?
intPersistant
PERINT=$?
if [ $TUNE -eq 0 ] && [ $PERINT -eq 0 ]; then # TUN interface exists & !persistant
    echo "Removing tun0 interface"
    openvpn --rmtun --dev tun0
fi