#!/bin/bash

#
#   DockerHub build hook (overrides default build command)
#   @see https://docs.docker.com/docker-hub/builds/advanced/
#   @see https://microbadger.com/labels
#

echo "Building image"

docker build \
    --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
    --build-arg VCS_REF=`git rev-parse --short HEAD` \
    --build-arg VCS_SRC="https://github.com/SloCompTech/docker-openvpn/commit/$SOURCE_COMMIT" \
    -t $IMAGE_NAME .