#!/usr/bin/with-contenv bash

#
#   Additional functions
#

function yn() {
    local defaultOption=${1:-'n'}
    local defaultText='[y/N]:'
    if [ defaultOption = 'y' ]; then
        defaultText='[Y/n]:'
    fi
    read -p "$defaultText" decision
    if [ "$decision" = 'y' ] || [ "$decision" = 'Y' ]; then
        echo '1'
    else
        echo '0'
    fi 
}

#
#   Checks if item is in array
#   @param $1 Array as "${array[@]}"
#   @param $2 String we are looking for
#   @return 0 If not in array, 1 if in array
#
#   arrayContains array "element"
#   echo $?
#
function arrayContains() {
    # Check if empty
    if [ ! -n "$1" ]; then
        return 0
    fi

    local array="$1[@]"
    # Check array for element
    for element in "${!array}"; do 
        
        # Check if we found element in array
        if [ "$2" = "$element" ]; then
            return 1
        fi
    done

    # Element not found
    return 0
}

#
#   Function that makes sure, that script runs only once
#   @param $1 ID
#
function run_once() {
    if [ -f "$1" ]; then # Check if file (as flag) exists
        exit 0
    fi
    touch $1 # Create flag
    chown abc:abc $1 # Change permission
}