#!/usr/bin/with-contenv bash
#
# OpenVPN service
#

if [ -n "$SKIP_APP" ]; then
  exit 0
fi

config=$(ovpn-confpath)
if [ -z "$config" ]; then
  read -p 'No configuration available'
  exit 0
fi

run-parts --exit-on-error $OPENVPN_DIR/hooks/start

openvpn --cd $OPENVPN_DIR --config $config

run-parts --exit-on-error $OPENVPN_DIR/hooks/stop
