#!/usr/bin/with-contenv bash

source /app/lib/settings

#
#   Network setup
#

# 
# 	Setup tunnel driver
#
#	@see https://help.skysilk.com/support/solutions/articles/9000136471-how-to-enable-tun-tap-on-linux-vps-with-skysilk
#	@see https://community.openvpn.net/openvpn/wiki/UnprivilegedUser
#	@see https://unix.stackexchange.com/questions/18215/which-user-group-can-use-the-tap-net-device
#
if [ ! -d "/dev/net" ]; then
	echo "Creating /dev/net"
	mkdir -p /dev/net
fi
if [ ! -c "/dev/net/tun" ]; then
	mknod /dev/net/tun c 10 200
	chmod 666 /dev/net/tun
fi

# Setup tun0 as tunnel interface
intTunExists
TUNE=$?
intPersistant
PERINT=$?
if [ $TUNE -eq 0 ] && [ $PERINT -eq 0 ]; then # TUN interface exists & !persistant
	echo "Removing tun0 interface"
	openvpn --rmtun --dev tun0
fi
if [ $TUNE -eq 1 ]; then # TUN interface !exist
	echo "Creating tun0 interface"
	openvpn --mktun --dev tun0 --dev-type tun --user abc --group abc
fi