#!/usr/bin/with-contenv bash

#
#	Link OpenVPN configs
#

LINK_FILE=/config/openvpn/include-conf.conf

# Build link file
echo "#" > $LINK_FILE
echo "# DO NOT EDIT" >> $LINK_FILE
echo "# Autogenerated file, based on /config/openvpn/config" >> $LINK_FILE
echo "#" >> $LINK_FILE
echo "" >> $LINK_FILE

for file in /config/openvpn/config/*
do
	[ -e "$file" ] || continue

	echo "config $file" >> $LINK_FILE
done

chown abc:abc $LINK_FILE
