#!/usr/bin/with-contenv bash

#
#	Dynamic OpenVPN configs
#

DYNAMIC_FILE=/config/openvpn/dynamic.conf

# Build link file
echo "#" > $DYNAMIC_FILE
echo "# DO NOT EDIT" >> $DYNAMIC_FILE
echo "# Autogenerated file, based on /config/openvpn/config" >> $DYNAMIC_FILE
echo "#" >> $DYNAMIC_FILE
echo "" >> $DYNAMIC_FILE

# Set interface name
echo "# Interface" >> $DYNAMIC_FILE
echo "dev $TUNNEL_INTERFACE" >> $DYNAMIC_FILE
echo "" >> $DYNAMIC_FILE

# Include all configuration files
for file in /config/openvpn/config/*
do
	[ -e "$file" ] || continue

	echo "config $file" >> $DYNAMIC_FILE
done

chown $CONTAINER_USER:$CONTAINER_USER $DYNAMIC_FILE
